spring.application.name=patient-service

# --- SERVER CONFIG ---
server.port=4000

## --- H2 DATABASE CONNECTION ---
#spring.datasource.url=jdbc:h2:mem:testDB
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
## --- H2 WEB CONSOLE ---
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## --- JPA / HIBERNATE CONFIG ---
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always


logging.level.root=info
